name: Restart Application on Azure VM

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.AZURE_VM_SSH_KEY }}
        
    - name: Restart Application
      run: |
        # Add VM host key to known hosts
        ssh-keyscan -H ${{ secrets.AZURE_VM_HOST }} >> ~/.ssh/known_hosts
        
        # SSH into VM and restart the application
        ssh ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }} << 'EOF'
          # Kill existing process if running
          PROCESS_PID=$(ps aux | grep "python3 main.py" | grep -v grep | awk '{print $2}')
          if [ ! -z "$PROCESS_PID" ]; then
            echo "Stopping existing process with PID: $PROCESS_PID"
            kill -9 $PROCESS_PID
          else
            echo "No existing process found"
          fi
          
          # Navigate to project directory
          cd ~/exAIma_backend
          
          # Ensure required packages are installed
          echo "Checking required system packages..."
          if ! dpkg -l | grep -qw python3-venv; then
            echo "Installing python3-venv package..."
            sudo apt update
            sudo apt install -y python3-venv python3-pip
          fi
          
          # Create and activate virtual environment if it doesn't exist
          if [ ! -d "venv" ]; then
            echo "Creating new virtual environment..."
            python3 -m venv venv
          fi
          source venv/bin/activate
          
          # Ensure dependencies are installed
          echo "Checking dependencies..."
          python3 -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            python3 -m pip install -r requirements.txt
          fi
          
          # Start application in background
          echo "Starting application..."
          nohup python3 main.py > app.log 2>&1 &
          
          # Verify process is running
          ps aux | grep "python3 main.py" | grep -v grep
          
          echo "Application restarted successfully"
        EOF